# Generated by Django 4.2.28 on 2026-02-25 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0298_alter_customer_locale_alter_user_locale'),
        ('pretix_event_analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(db_index=True, max_length=32)),
                ('identity_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Identity',
                'verbose_name_plural': 'Analytics Identities',
            },
        ),
        migrations.RenameIndex(
            model_name='analyticsorderfact',
            new_name='pretix_even_event_i_b84368_idx',
            old_name='aof_event_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsorderfact',
            new_name='pretix_even_repeat__c13f1e_idx',
            old_name='aof_repeat_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsorderfact',
            new_name='pretix_even_country_a3cfd5_idx',
            old_name='aof_country_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsorderfact',
            new_name='pretix_even_order_d_ba71ff_idx',
            old_name='aof_order_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsorderfact',
            new_name='pretix_even_event_i_13a9c7_idx',
            old_name='aof_event_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsorderfact',
            new_name='pretix_even_event_i_be7a27_idx',
            old_name='aof_event_year_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsorderfact',
            new_name='pretix_even_event_i_da95d8_idx',
            old_name='aof_event_country_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsorderfact',
            new_name='pretix_even_series__4141ff_idx',
            old_name='aof_series_year_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsorderfact',
            new_name='pretix_even_organiz_57249b_idx',
            old_name='aof_org_series_year_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsticketfact',
            new_name='pretix_even_event_i_b9d905_idx',
            old_name='atf_event_item_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsticketfact',
            new_name='pretix_even_order_f_ceb372_idx',
            old_name='atf_order_fact_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsticketfact',
            new_name='pretix_even_event_i_b1016c_idx',
            old_name='atf_event_addon_idx',
        ),
        migrations.RenameIndex(
            model_name='eventseries',
            new_name='pretix_even_organiz_d70200_idx',
            old_name='analytics_series_org_slug_idx',
        ),
        migrations.AlterField(
            model_name='analyticsorderfact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='analyticsticketfact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventanalyticsconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='analyticsidentity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_identities', to='pretixbase.event'),
        ),
        migrations.AddField(
            model_name='analyticsidentity',
            name='order_fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='pretix_event_analytics.analyticsorderfact'),
        ),
        migrations.AddIndex(
            model_name='analyticsidentity',
            index=models.Index(fields=['event', 'identity_type', 'identity_hash'], name='pretix_even_event_i_474efc_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsidentity',
            index=models.Index(fields=['identity_hash', 'identity_type'], name='pretix_even_identit_13cb2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticsidentity',
            unique_together={('order_fact', 'identity_type', 'identity_hash')},
        ),
    ]
