# Generated by Django 4.2.28 on 2026-09-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0001_initial'),  # plugin only needs Event/Organizer; never pin a recent core migration
        ('pretix_event_analytics', '0004_performance_and_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsAnswerFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question_id', models.IntegerField()),
                ('question_label', models.CharField(max_length=255)),
                ('answer_value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Analytics Answer Fact',
                'verbose_name_plural': 'Analytics Answer Facts',
            },
        ),
        migrations.CreateModel(
            name='LegacyEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('edition_year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legacy edition',
                'verbose_name_plural': 'Legacy editions',
                'ordering': ('edition_year', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='LegacyIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(default='email', max_length=32)),
                ('identity_hash', models.CharField(db_index=True, max_length=64)),
                ('person_key', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='analyticsticketfact',
            name='unique_ticket_per_order_item',
        ),
        migrations.RenameIndex(
            model_name='analyticsorderfact',
            new_name='pretix_even_event_i_94862c_idx',
            old_name='pretix_even_event_i_status_idx',
        ),
        migrations.AddField(
            model_name='analyticsidentity',
            name='ticket_fact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='pretix_event_analytics.analyticsticketfact'),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='addon_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='days_before_event',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='editions_attended',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='fact_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='fees_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='has_addons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='is_local_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='person_key',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='voucher_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='attendee_editions_attended',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='attendee_first_seen_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='attendee_identified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='attendee_is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='attendee_person_key',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='attendee_previous_editions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='first_checkin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='is_returning_attendee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='item_category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='position_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='voucher_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='voucher_tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eventanalyticsconfig',
            name='revenue_target',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='eventanalyticsconfig',
            name='ticket_target',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventanalyticsconfig',
            name='tracked_question_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name='analyticsticketfact',
            constraint=models.UniqueConstraint(condition=models.Q(('position_id__isnull', False)), fields=('order_fact', 'position_id'), name='unique_ticket_per_position'),
        ),
        migrations.AddField(
            model_name='legacyidentity',
            name='legacy_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='pretix_event_analytics.legacyedition'),
        ),
        migrations.AddField(
            model_name='legacyedition',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_editions', to='pretix_event_analytics.eventseries'),
        ),
        migrations.AddField(
            model_name='analyticsanswerfact',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_answer_facts', to='pretixbase.event'),
        ),
        migrations.AddField(
            model_name='analyticsanswerfact',
            name='ticket_fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pretix_event_analytics.analyticsticketfact'),
        ),
        migrations.AddConstraint(
            model_name='legacyidentity',
            constraint=models.UniqueConstraint(fields=('legacy_edition', 'identity_type', 'identity_hash'), name='unique_legacy_identity'),
        ),
        migrations.AddIndex(
            model_name='analyticsanswerfact',
            index=models.Index(fields=['event', 'question_id'], name='pretix_even_event_i_522c6a_idx'),
        ),
    ]
