# Generated by Django 4.2.28 on 2026-09-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_event_analytics', '0005_suite_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventanalyticsconfig',
            name='people_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
