# Generated by Django 4.2.28 on 2026-09-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0298_alter_customer_locale_alter_user_locale'),
        ('pretix_event_analytics', '0006_people_resolved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_annotations', to='pretixbase.event')),
            ],
            options={
                'verbose_name': 'Sales annotation',
                'verbose_name_plural': 'Sales annotations',
                'ordering': ('date', 'pk'),
            },
        ),
    ]
