# Generated by Django 4.2.28 on 2026-09-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_event_analytics', '0007_sales_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventanalyticsconfig',
            name='pace_alert_last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventanalyticsconfig',
            name='pace_alert_recipients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eventanalyticsconfig',
            name='pace_alert_threshold',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
