# Generated by Django 4.2.28 on 2026-09-25 18:16

from django.db import migrations, models


def dedupe_for_rollback(apps, schema_editor):
    """
    Reverse only: 2.1 allows one signal per *ticket*, 2.0 one per *order*.
    Keep the first row of each (order, type, hash) so the old constraint can
    return; a resync on the older version rebuilds the rest.
    """
    from django.db.models import Min

    Identity = apps.get_model("pretix_event_analytics", "AnalyticsIdentity")
    keep = Identity.objects.values("order_fact_id", "identity_type", "identity_hash").annotate(keep=Min("id"))
    keep_ids = {r["keep"] for r in keep}
    stale = [pk for pk in Identity.objects.values_list("id", flat=True) if pk not in keep_ids]
    for i in range(0, len(stale), 1000):
        Identity.objects.filter(pk__in=stale[i:i + 1000]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_event_analytics', '0008_pace_alerts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analyticsidentity',
            name='unique_identity_per_order',
        ),
        migrations.RunPython(migrations.RunPython.noop, dedupe_for_rollback),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='country_source',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='travel_country_code',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='attendee_match',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='attendee_person_key_incl',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='document_country',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='is_returning_attendee_incl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventanalyticsconfig',
            name='id_question_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='legacyidentity',
            name='entry',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='analyticsidentity',
            constraint=models.UniqueConstraint(fields=('order_fact', 'ticket_fact', 'identity_type', 'identity_hash'), name='unique_identity_per_ticket'),
        ),
    ]
