# Generated by Django 4.2.28 on 2026-09-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_event_analytics', '0009_accuracy_2_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsorderfact',
            name='bank_country',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='bank_country_source',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='analyticsorderfact',
            name='nationality',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='nationality',
            field=models.CharField(db_index=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='analyticsticketfact',
            name='nationality_source',
            field=models.CharField(default='', max_length=20),
        ),
    ]
